name: cicd

on:
  push:
    paths:
      - app/**
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dcaroc/fast-api-docker:${{ env.sha_short }}
    outputs:
      commit_id: ${{ env.sha_short }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          python-version: '3.11'
      - name: Modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          pip install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-app/values.yaml
      - name: Commit change
        uses: EndBug/add-and-commit@v9
        with:
          message: "CD key of chart values commit ${{needs.ci.outputs.commit_id}}"
      - name: Install Argo
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      - name: ArgoCD deployment
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web  \
            --username ${{ secrets.ARGOCD_USERNAME }}\
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app
